# Generated by Django 4.2.7 on 2023-12-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="photo",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
