# Generated by Django 4.2.7 on 2023-12-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(upload_to="videos/"),
        ),
    ]
