# Generated by Django 4.2.7 on 2023-12-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_video_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="time",
            field=models.TimeField(auto_now=True),
        ),
    ]
