# Generated by Django 4.2.7 on 2023-12-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_video_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
