# Generated by Django 5.0 on 2024-01-04 16:22

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_audio_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=base.models.UUIDStorage,
                upload_to="avatars/",
            ),
        ),
    ]
