# Generated by Django 4.2.7 on 2023-12-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_video_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="image",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
