# Generated by Django 4.2.7 on 2023-12-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_audio_time_image_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="time",
        ),
        migrations.RemoveField(
            model_name="video",
            name="time",
        ),
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="video",
            name="fps",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="frames",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
