# Generated by Django 4.2.7 on 2023-12-20 07:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_remove_image_time_remove_video_time_video_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="fps",
        ),
        migrations.RemoveField(
            model_name="video",
            name="frames",
        ),
    ]
