# Generated by Django 4.2.7 on 2023-12-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_remove_video_fps_remove_video_frames"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="fps",
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="frames",
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
