# Generated by Django 4.2.7 on 2023-12-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_video_fps_video_frames"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="fps",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="frames",
            field=models.IntegerField(),
        ),
    ]
