# Generated by Django 4.2.7 on 2023-12-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_alter_video_fps_alter_video_frames"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="height",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="width",
            field=models.IntegerField(null=True),
        ),
    ]
