# Generated by Django 4.2.7 on 2023-12-20 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_alter_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
