# Generated by Django 4.2.7 on 2023-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_alter_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
