# Generated by Django 4.2.7 on 2023-12-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_alter_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
