# Generated by Django 4.2.7 on 2023-12-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0020_alter_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
