# Generated by Django 4.2.7 on 2023-12-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0021_alter_video_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="duration",
            field=models.DurationField(null=True),
        ),
    ]
