# Generated by Django 4.2.7 on 2023-12-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0022_alter_video_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="grayscale",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/grayscale/"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="normalization",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/normalization/"
            ),
        ),
    ]
