# Generated by Django 4.2.7 on 2023-12-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0024_video_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="videos/cover/"),
        ),
    ]
