# Generated by Django 5.0 on 2023-12-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0025_alter_video_cover"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio",
            name="time",
        ),
        migrations.AddField(
            model_name="audio",
            name="spectrogram",
            field=models.ImageField(
                blank=True, null=True, upload_to="audios/spectrogram"
            ),
        ),
        migrations.AddField(
            model_name="audio",
            name="spectrum_diagram",
            field=models.ImageField(
                blank=True, null=True, upload_to="audios/spectrum_diagram"
            ),
        ),
    ]
