# Generated by Django 5.0 on 2023-12-23 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0026_remove_audio_time_audio_spectrogram_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio",
            name="spectrum_diagram",
        ),
    ]
