# Generated by Django 5.0 on 2023-12-23 03:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0027_remove_audio_spectrum_diagram"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
