# Generated by Django 5.0 on 2023-12-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0028_audio_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="spectrum_diagram",
            field=models.ImageField(
                blank=True, null=True, upload_to="audios/spectrum_diagram"
            ),
        ),
    ]
