# Generated by Django 5.0 on 2023-12-25 12:01

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0029_audio_spectrum_diagram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="audio",
            field=models.FileField(
                storage=base.models.UUIDStorage, upload_to="audios/"
            ),
        ),
        migrations.AlterField(
            model_name="audio",
            name="spectrogram",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=base.models.UUIDStorage,
                upload_to="audios/spectrogram/",
            ),
        ),
        migrations.AlterField(
            model_name="audio",
            name="spectrum_diagram",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=base.models.UUIDStorage,
                upload_to="audios/spectrum_diagram/",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="grayscale",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=base.models.UUIDStorage,
                upload_to="images/grayscale/",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="normalization",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=base.models.UUIDStorage,
                upload_to="images/normalization/",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="photo",
            field=models.ImageField(
                storage=base.models.UUIDStorage, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=base.models.UUIDStorage,
                upload_to="videos/cover/",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                storage=base.models.UUIDStorage, upload_to="videos/"
            ),
        ),
    ]
