# Generated by Django 5.0 on 2024-01-03 12:47

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0030_alter_audio_audio_alter_audio_spectrogram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="grayscaleProcessed",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=base.models.UUIDStorage,
                upload_to="images/gray/",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="normalizationProcessed",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=base.models.UUIDStorage,
                upload_to="images/normalized/",
            ),
        ),
    ]
