# Generated by Django 5.0 on 2024-01-03 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0033_video_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="user",
        ),
    ]
